### ISSUE TITLE
The assembly is not signed

### ISSUE THREAD

**Issue by jucamo8311** [StefH/Handlebars.Net.Helpers#10]
Hi , 

I was trying to use WireMock.Net , this library use underneath "Handlebars.Net.Helpers" for some scenarios , 
that's why I am here .

WireMock.Net is a sign library , when tries to load "Handlebars.Net.Helpers" break down because for restrictions looks like a sign library can't not open a library witch is not 

_Exception: System.IO.FileLoadException: Could not load file or assembly 'Handlebars.Net.Helpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'Handlebars.Net.Helpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'_

 is any way for you to generate the nugets packages with the library sign?, most of the nugets libraries come this way.

Any open source projects that uses this library underneath  will have the same problem if  their library is sign.

Thanks

**Comment by StefH** [comment]
Hello @jucamo8311, what .NET framework do you use ?

**Comment by StefH** [comment]
#11 

Can you try MyGet version : 
`Handlebars.CSharp.Helpers.1.1.0-ci-13856.nupkg`

(https://github.com/StefH/Handlebars.Net.Helpers/wiki/MyGet)

**Comment by jucamo8311** [comment]
> Hello @jucamo8311, what .NET framework do you use ?

Hi , .net framework 4.5.2.

**Comment by StefH** [comment]
Are you able to test that NuGet version from MyGet ?

**Comment by jucamo8311** [comment]
> t that NuGet version from MyGet ?

Yes, it does the trick. Although I had to build Wiremock.net by myself using Handlebars.CSharp.Helpers.1.1.0-ci-13856.nupkg as a dependency.

**Comment by StefH** [comment]
Yes, once Handlebars.Net.Helpers is published, I'll update WireMock.Net

Thanks for verifying.

**Comment by StefH** [comment]
@jucamo8311 WireMock.Net is also updated.
