### ISSUE TITLE
Compatibility with Handlebarsjs (and Handlerbars.CSharp)?

### ISSUE THREAD

**Issue by zjklee** [StefH/Handlebars.Net.Helpers#7]
## The problem

According to [`Handlebars helper documentation`](https://handlebarsjs.com/guide/expressions.html#helpers):
>A Handlebars helper call is a simple identifier, followed by zero or more parameters

and [Identifier definition](https://handlebarsjs.com/guide/expressions.html#literal-segments):
> Identifiers may be any unicode character except for the following:
Whitespace ! " # % & ' ( ) * + , . / ; < = > @ [ \ ] ^ ` { | } ~

It looks like usage example is not valid:
```handlebars
{{String.Append "foobar" "bar"}}
```
In order to be rendered correctly it should be:
```handlebars
{{[String.Append] "foobar" "bar"}}
```

Simple example of Handlebarsjs behavior using suggested syntax: https://jsfiddle.net/bc89sjmg/1/ 
- Expected:
  - `AAA` - printed **twice**
  - `BBB` - printed once
- Actual:
  - `AAA` - printed **once**
  - `BBB` - printed once

In [Handlerbars.CSharp](https://github.com/zjklee/Handlebars.CSharp) I've followed the same approach to be as close to Handlebarsjs as possible. Changes related to the topic were made in zjklee/Handlebars.CSharp/pull/20 and zjklee/Handlebars.CSharp/pull/21

**Comment by StefH** [comment]
@zjklee This is only for normal helpers, not for block-helpers? Correct?

**Comment by StefH** [comment]
https://github.com/StefH/Handlebars.Net.Helpers/pull/8

**Comment by zjklee** [comment]
> @zjklee This is only for normal helpers, not for block-helpers? Correct?

Unfortunately this is true also for block helpers.

**Comment by zjklee** [comment]
I assume that a lot of users rely on this behavior so I consider adding compatibility switch to Handlebars that would allow using helpers as before.

**Comment by StefH** [comment]
How would this template be used when using a prefix of "String." ?
```
"{{#StartsWith \"Hello\" \"x\"}}Hi{{else}}Goodbye{{/StartsWith}}"
```

`"{{#String.StartsWith \"Hello\" \"x\"}}Hi{{else}}Goodbye{{/String.StartsWith}}"` does not work?

**Comment by zjklee** [comment]
@StefH Unfortunately it wouldn't work with prefix - take a loot at an example: https://jsfiddle.net/bc89sjmg/2/
- Expected:
  - aaa
  - bbb
- Actual:
  - bbb

As a valid alternative to prefixes separated by `.` I may recommend using `-` instead, see https://jsfiddle.net/bc89sjmg/3/

**Comment by StefH** [comment]
In this library, I'll also add a `PrefixSeparator` option which can be set to any value, default however will be a dot `.`.
