### ISSUE TITLE
Enumerable.Select

### ISSUE THREAD

**Issue by mvroone** [StefH/Handlebars.Net.Helpers#9]
In the Wiki there is some documentation about the Enumerable.Select helper. When i try to implement the Example given, an exception is raised: Template references a helper that is not registered. Could not find helper '#Enumerable.Select'

What is the status of the Enumerable.Select helper, will it be implemented or is the documentation on the Wiki not accurate.

**Comment by StefH** [comment]
Hello @mvroone, it seems that the Wiki is incorrect, the `Select` is not yet implemented.

I'll take a look how to implement this.

**Comment by StefH** [comment]
https://github.com/StefH/Handlebars.Net.Helpers/pull/12

**Comment by StefH** [comment]
@mvroone I did implement the *Select*, can you please test MyGet version: `Handlebars.Net.Helpers.1.1.0-ci-13872`?

**Comment by mvroone** [comment]
@StefH I tested the version, seems to be working fine. Had a small issue when nesting selects and the nested collection being null, but that can be solved with an if. So not sure if you consider it to be an issue.

**Comment by StefH** [comment]
@mvroone Thanks for testing. A new version will be released on NuGet.
